blank_issues_enabled: false # "ë¹ˆ ì´ìŠˆ" ì‘ì„± ë²„íŠ¼ ë¹„í™œì„±í™”

templates:
  - name: ğŸ› Bug Report
    about: ë²„ê·¸ë¥¼ ì‹ ê³ í•˜ê³  ë¬¸ì œë¥¼ í•´ê²°í•˜ëŠ” ë° ë„ì›€ì„ ì£¼ì„¸ìš”.
    file: bug_report.md

  - name: âœ¨ Feature Request
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ ì•„ì´ë””ì–´ë¥¼ ì œì•ˆí•˜ê±°ë‚˜ ê¸°ì¡´ ê¸°ëŠ¥ ê°œì„  ë°©ì•ˆì„ ì œì‹œí•´ì£¼ì„¸ìš”.
    file: feature_suggestion.md

  - name: â“ Question / Help
    about: í”„ë¡œì íŠ¸ì— ëŒ€í•œ ì§ˆë¬¸ì´ë‚˜ ë„ì›€ì´ í•„ìš”í•œ ë‚´ìš©ì„ ì‘ì„±í•´ì£¼ì„¸ìš”.
    file: question.md

  - name: âœ… Task
    about: ìˆ˜í–‰í•´ì•¼ í•  ì‘ì—…ì´ë‚˜ ìš”ì²­ì‚¬í•­ì„ ë“±ë¡í•´ì£¼ì„¸ìš”.
    file: task_request.md

  - name: ğŸ“ Documentation
    about: ë¬¸ì„œ ê°œì„ ì´ë‚˜ ì¶”ê°€ê°€ í•„ìš”í•œ ë¶€ë¶„ì„ ì•Œë ¤ì£¼ì„¸ìš”.
    file: documentation.md
